### ISSUE TITLE
Troubleshooting guide

### ISSUE THREAD

**Issue by christoferlof** [magicaks/magicaks#60]
We have one issue related to terraform that should be added to the guide

**Comment by TessFerrandez** [comment]
Also: if this happens in step 2 (for any of the scripts)

Error: Error running command '/mnt/c/<repo>/2-provision-aks/getcreds.sh <cluster rg> <kubernetes service>': exit status 127. Output: /bin/sh: 1: /mnt/c/<repo>/2-provision-aks/getcreds.sh: not found

"We know it's the 21 century, but check the line endings."  they should be LF instead of CRLF (this may happen if you clone the repo from windows for example.) - check the line endings of all sh files in the repo at once and set them to LF

**Comment by TessFerrandez** [comment]
The error that the original text is referring to is:

Error: failed to create resource: namespaces "app1" not found

This is due to a timing issue where app1 is not yet created - Wait a few minutes and rerun the apply, and it should work
